spring:
  datasource:
    url: jdbc:mysql://localhost:3306/social_network?&createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Moscow
    username: root
    password: testtest
  jpa:
    hibernate.ddl-auto: none
    properties.hibernate.dialect: org.hibernate.dialect.MySQL55Dialect

    properties:
      hibernate:
        globally_quoted_identifiers: true

jwt.token:
  secret: jwtappdemo
  expired: 3600000

server:
  port: 8080

upload:
  path: "C:/Users/Valet/Desktop/storage"