spring.datasource.url: jdbc:mysql://localhost:3306/social_network?allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&useUnicode=true&useSSL=false&serverTimezone=Europe/Moscow&characterEncoding=utf8
spring.datasource.username: root
spring.datasource.password: testtest
spring.jpa.hibernate.ddl-auto: update