spring.datasource.url: jdbc:mysql://localhost:3306/social_network?createDatabaseIfNotExist=true&useUnicode=true&useSSL=false&serverTimezone=Europe/Moscow&characterEncoding=utf8
spring.datasource.username: root
spring.datasource.password: 1234
spring.jpa.hibernate.ddl-auto: none
